defaults:
  - default
  - _self_

# Override from `default` config
id: autodrive
num_envs: 1
capture_video: False

# Wrapper to be instantiated
wrapper:
  _target_: sheeprl.envs.autodrive.AutoDRIVEWrapper