defaults:
  - default
  - _self_

action_repeat: 2
max_episode_steps: 500

env:
  _target_: sheeprl.envs.dmc.DMCWrapper
  id: walker_walk
  height: ${env.screen_size}
  width: ${env.screen_size}
  frame_skip: ${env.action_repeat}
  seed: null
  from_pixels: True
