defaults:
  - minecraft
  - _self_

action_repeat: 1

env:
  _target_: sheeprl.envs.minerl.MineRLWrapper
  id: custom_navigate
  height: ${env.screen_size}
  width: ${env.screen_size}
  pitch_limits:
    - ${env.min_pitch}
    - ${env.max_pitch}
  seed: null
  break_speed_multiplier: ${env.break_speed_multiplier}
  sticky_attack: ${env.sticky_attack}
  sticky_jump: ${env.sticky_jump}
  dense: True
  extreme: False
