defaults:
  - sac
  - /optim@ensembles.optimizer: adam
  - _self_

name: mopo

# Algorithm-related paramters
total_steps: 1_000_000 # SAC updates
h: 1 # Rollout length
num_epochs: 1000
per_rank_rollout_batch_size: 50_000
per_rank_batch_size: 256 # SAC
mlp_keys:
  encoder: [observations]
cnn_keys:
  encoder: []

# World model parameters
ensembles:
  mlp_layers: 4
  dense_units: 200
  dense_act: torch.nn.SiLU
  num_ensembles: 7
  num_elites: 5
  penalty_coef: 2.0
  per_rank_batch_size: 512
  max_epochs: null
  max_epochs_since_update: 5

  # Override parameters coming from `adam.yaml` config
  optimizer:
    lr: 1e-3
    eps: 1e-4
    weight_decays: [2.5e-05, 5e-05, 7.5e-05, 7.5e-05, 1e-4]
