defaults:
  - default
  - sac
  - /optim@ensembles.optimizer: adam
  - _self_

name: mopo # This must be set! And must be equal to the name of the file.py, found under the `my_awesome_algo` folder, where the implementation of the algorithm is defined

# Algorithm-related paramters
h: 1 # Rollout length
num_epochs: 1000
rollout_batch_size: 50_000
epoch_length: 1000
per_rank_batch_size: 256
mlp_keys:
  encoder: [observations]
cnn_keys:
  encoder: []

# Agent model parameters
# This is just an example where we suppose we have an Actor-Critic agent
# with both an MLP and a CNN encoder
ensembles:
  mlp_layers: 4
  dense_units: 200
  dense_act: torch.nn.SiLU
  num_ensembles: 7
  num_elites: 5
  penalty_coef: 1.0
  batch_size: 512

  # Override parameters coming from `adam.yaml` config
  optimizer:
    lr: 1e-3
    eps: 1e-4
    weight_decays: [2.5e-05, 5e-05, 7.5e-05, 7.5e-05, 1e-4]
