defaults:
  - ppo
  - _self_

name: ppo_recurrent
reset_recurrent_state_on_done: False

lstm:
  hidden_size: ${algo.dense_units}

actor:
  pre_lstm_hidden_size: ${algo.dense_units}

critic:
  pre_lstm_hidden_size: ${algo.dense_units}