# @package _global_

defaults:
  - override /algo: dreamer_v1
  - override /env: dmc
  - _self_

per_rank_batch_size: 50
per_rank_sequence_length: 50
total_steps: 5000000
checkpoint:
  every: 100000
buffer:
  size: 5000000
  checkpoint: False
  memmap: True
