# @package _global_

defaults:
  - override /algo: dreamer_v2
  - override /env: atari
  - _self_

per_rank_batch_size: 16
per_rank_sequence_length: 50
total_steps: 5000000
checkpoint:
  every: 100000
buffer:
  size: 5000000
  type: sequential
  prioritize_ends: False
  checkpoint: False
  memmap: True
