# @package _global_

defaults:
  - override /algo: dreamer_v1
  - override /env: dmc
  - _self_

per_rank_batch_size: 50
per_rank_sequence_length: 50
total_steps: 5000000
buffer_size: 5000000
learning_starts: 5000
gradient_steps: 100
train_every: 1000
use_continues: False

# override
memmap_buffer: True