# @package _global_

defaults:
  - dreamer_v3
  - override /env: diambra 
  - _self_

env:
  env:
    id: doapp
    diambra_settings:
      characters: Kasumi

seed: 5
num_envs: 16
checkpoint_every: 200000
total_steps: 5000000
train_every: 4
buffer:
  checkpoint: True

# the CNN and MLP keys of the decoder are the same as those of the encoder by default
cnn_keys:
  encoder: 
    - frame
mlp_keys:
  encoder:
    - P1_actions_attack
    - P1_actions_move
    - P1_oppChar
    - P1_oppHealth
    - P1_oppSide
    - P1_oppWins
    - P1_ownChar
    - P1_ownHealth
    - P1_ownSide
    - P1_ownWins
    - stage

algo:
  dense_units: 768
  mlp_layers: 4
  world_model:
    encoder:
      cnn_channels_multiplier: 64
    recurrent_model:
      recurrent_state_size: 2048
    transition_model:
      hidden_size: 768
    representation_model:
      hidden_size: 768
