# @package _global_

defaults:
  - override /algo: dreamer_v3
  - override /env: atari
  - _self_

per_rank_batch_size: 16
per_rank_sequence_length: 64
total_steps: 5000000
checkpoint:
  every: 100000
buffer:
  size: 1000000
  checkpoint: False
  memmap: True
learning_starts: 65536
pretrain_steps: 1
gradient_steps: 1
train_every: 16
