# @package _global_

defaults:
  - dreamer_v3
  - override /env: atari
  - _self_

env:
  id: MsPacmanNoFrameskip-v4
  max_episode_steps: 27000

seed: 5
num_envs: 1
checkpoint_every: 2000
total_steps: 100000
train_every: 1
buffer:
  size: 200000
  checkpoint: True

algo:
  dense_units: 512
  mlp_layers: 2
  world_model:
    encoder:
      cnn_channels_multiplier: 32
    recurrent_model:
      recurrent_state_size: 512
    transition_model:
      hidden_size: 512
    representation_model:
      hidden_size: 512
