# @package _global_

defaults:
  - mopo
  - _self_

algo:
  h: 1 # Rollout length
  ensembles:
    penalty_coef: 1.0

# override environment id
env:
  id: walker2d-medium-v0

fabric:
  accelerator: cuda
