# @package _global_

defaults:
  - override /algo: mopo
  - override /env: gym
  # select the model manager configs
  - override /model_manager: default
  - _self_

algo:
  total_steps: 0

buffer:
  size: 2_000_000
  share_data: False

# override environment id
env:
  id: halfcheetah-medium-v0

fabric:
  accelerator: cuda

metric:
  aggregator:
    metrics:
      # SAC Losses
      Loss/value_loss:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
      Loss/policy_loss:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
      Loss/alpha_loss:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
      # MOPO Losses
      Loss/train_world_model:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
      Loss/validation_world_model:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
      Grads/world_model:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
