# @package _global_

defaults:
  - override /algo: muzero
  - override /env: gym
  - _self_

# Experiment
total_steps: 6000
learning_starts: 6000
update_epochs: 10
chunk_sequence_len: 10
chunks_per_batch: 128

# Buffer
buffer:
  size: 10000
  share_data: False
  max_trajectory_len: 1000
  memmap: False

algo:
  support_size: 20
  gamma: 0.999

env:
  id: LunarLander-v2