# @package _global_

defaults:
  - override /algo: muzero
  - override /env: gym
  - _self_

# Experiment
total_steps: 1000
learning_starts: 1
update_epochs: 10
chunk_sequence_len: 10
chunks_per_batch: 128

# Buffer
buffer:
  size: 500000
  share_data: False
  max_trajectory_len: 500