# @package _global_

defaults:
  - override /algo: ppo_np
  - override /env: gym
  - _self_

# Experiment
total_steps: 65536
per_rank_batch_size: 64

# Buffer
buffer:
  share_data: False
  size: ${algo.rollout_steps}

metric:
  log_every: 32768