# @package _global_

defaults:
  - rlhf_default
  - /model: opt
  - /generation: default
  - /data: helpful_harmless
  - /optim: adamw
  - override /algo: rlhf_sft
  - override /fabric: ddp-cuda
  - _self_

fabric:
  devices: 1
