# @package _global_

defaults:
  - rlhf_default
  - /model: opt
  - /generation: default
  - /data: helpful_harmless
  - /optim: adamw
  - override /algo: rlhf_dpo
  - _self_

sft_experiment_dir: null

fabric:
  devices: 1
