# @package _global_

defaults:
  - override /env: atari
  - override /algo: storm
  - _self_

# Experiment
seed: 5
total_steps: 100000

# Environment
env:
  num_envs: 1
  max_episode_steps: 27000
  id: MsPacmanNoFrameskip-v4

# Checkpoint
checkpoint:
  every: 2000

# Buffer
buffer:
  size: 100000
  checkpoint: True

# Algorithm
algo:
  cnn_keys:
      encoder: [rgb]
      decoder: [rgb]
  learning_starts: 1024
  total_steps: 100000
  per_rank_batch_size: 64
  train_every: 1
  dense_units: 512
  mlp_layers: 2
  world_model:
    encoder:
      cnn_channels_multiplier: 32
